var ArrayUsers = [
  {
    name: "Lucas Gonçalves",
    area: "Desenvolvedor Web",
    description: "<p>Meu nome é Lucas Gonçalves, sou um desenvolvedor web autodidata que vive nos estado de Minas Gerais. Profissionalmente conectado com a indústria de software, interessado no escopo Front-End.</p>",
    image: "https://firebasestorage.googleapis.com/v0/b/techtuais-a0e95.appspot.com/o/LucasGon%C3%A7alves.png?alt=media&token=0b753ae7-cb4f-4993-b8b2-40be6ecf9d77",
    github: "https://github.com/Lucas-Eduardo-Goncalves",
    linkedin: "https://www.linkedin.com/in/lucas-gon%C3%A7alves-62a16b209",
    curriculo: "https://drive.google.com/file/d/1Uv5_l6RuUHypMVCpRvJi9lK825xyTYHS/view?usp=sharing"
  },
  {
    name: "Camila Silva",
    area: "HTML5",
    description: "<p>Sou a Camila, tenho 19 anos e sou de Uauá-BA. Terminei o ensino médio técnico em informática, que foi meu primeiro contato com a área. Sou bem responsável, bem decidida, sempre em busca de mais conhecimento.</p> ",
    image: "https://firebasestorage.googleapis.com/v0/b/techtuais-a0e95.appspot.com/o/Camila.jpg?alt=media&token=27e0e929-6e76-415d-85b7-4ea05eb33f12",
    github: "https://github.com/camilaalves002",
    linkedin: "https://www.linkedin.com/in/camila-alves-82a794224",
    curriculo: "https://drive.google.com/file/d/1QsAUoOoErdONTZeyrxarxxIA6OFrAnrV/view?usp=drivesdk"
  },
  {
    name: "Davi Nascimento",
    area: "HTML5",
    description: "<p>Me chamo Davi, tenho 15 anos, moro em Vitória da Conquista-BA. Cursando o ensino médio, fascinado pelo processo de aprender. Atuo como designer e coordenador de conteúdo. Planejo seguir na área como programador Front-End.</p>",
    image: "https://firebasestorage.googleapis.com/v0/b/techtuais-a0e95.appspot.com/o/DaviNascimento.png?alt=media&token=fe3b6652-baf5-4c0e-857e-582408048edc",
    github: "https://github.com/nDavii",
    linkedin: "https://www.linkedin.com/in/davi-nascimento-11a900226/",
    curriculo: "https://drive.google.com/file/d/1wX22__6dI6wURRIQVLLO6KYansLQpO-I/view?usp=sharing",
  },
  {
    name: "Élson Endell",
    area: "UX/UI Design",
    description: "<p>Sou o Élson, tenho 18 anos, moro em Timon-MA. A tecnologia é o futuro de todas as profissões. Extremamente dinâmico, administração, trabalho em equipe.</p>",
    image: "https://firebasestorage.googleapis.com/v0/b/techtuais-a0e95.appspot.com/o/ElsonV2.jpg?alt=media&token=b0671f7b-a647-4331-b00c-995aa55146f7",
    github: "https://github.com/elson-endell",
    linkedin: "https://www.linkedin.com/in/élson-endell-38837a225/",
    curriculo: "https://drive.google.com/file/d/11I0Pg3-siX3-V4lQUwnXf7KVc-01AOnf/view?usp=sharing",
  },
  {
    name: "Evellyn Yokoyama",
    area: "UX/UI Design",
    description: "<p>Sou a Evellyn, tenho 17 anos, moro em Goiânia-Go. Estou me aventurando na área da tecnologia. Facilidade em trabalho em equipe, comunicação e criatividade.</p>",
    image: "https://firebasestorage.googleapis.com/v0/b/techtuais-a0e95.appspot.com/o/EvellynV2.jpg?alt=media&token=1f9023af-f33d-4bd2-b7af-abd976514acf",
    github: "https://github.com/Evellym",
    linkedin: "https://www.linkedin.com/in/evellyn-mayumi-230795224/",
    curriculo: "https://drive.google.com/file/d/11FgrTnb0jAcezKTfweL-20mq9BJrvy63/view?usp=sharing",
  },
  {
    name: "Fabyola Campos",
    area: "HTML5",
    description: "<p>Sou a Fabyola, moro Virgem da Lapa (Minas Gerais). Sempre busquei aprender coisas novas e meu amor pela programação foi graças aos vários benefícios dela em nossa vida. Facilidade em gestão de tempo, comunicação, flexibilidade.</p>",
    image: "https://firebasestorage.googleapis.com/v0/b/techtuais-a0e95.appspot.com/o/Fabyola.v2.jpg?alt=media&token=0bdfb1a8-55dd-4132-9af0-a1c6bef0350b",
    github: "https://github.com/fabyolaf",
    linkedin: "https://www.linkedin.com/in/fabyola-campos",
    curriculo: "https://docs.google.com/document/d/10e41qqGpx_94kvxYmvAk7EH2WrkbJ21m/edit?usp=sharing&ouid=111703281369057805072&rtpof=true&sd=true",
  },
  {
    name: "Felipe Souza",
    area: "Javascript",
    description: "<p>Me chamo Felipe tenho 18 anos, sou de Ibirité-MG. Cursando Técnico em Mecatrônica. Gosto sempre de estar aprendendo e evoluindo. Facilidade em gestão de pessoas, marketing, inglês.</p>",
    image: "https://firebasestorage.googleapis.com/v0/b/techtuais-a0e95.appspot.com/o/FelipeSouzaV2.webp?alt=media&token=8d3054fc-536e-49ea-b66c-79489934b35a",
    github: "https://github.com/Lype358",
    linkedin: "https://www.linkedin.com/in/felipe-de-souza-pereira-b85106224/",
    curriculo: "https://drive.google.com/file/d/1713DDwTAtW7uXj0qAH5Lx9A0DkFp1ldu/view?usp=sharing",
  },
  {
    name: "Pâmela Sales",
    area: "Javascript",
    description: "<p>Sou a Pâmela, tenho 16 anos e moro em Belo Horizonte-MG Estudante do ensino médio, sempre em busca de conhecimento. Facilidade em comunicação e produtividade.</p>",
    image: "https://firebasestorage.googleapis.com/v0/b/techtuais-a0e95.appspot.com/o/PamelaV2.jpg?alt=media&token=4f90d271-788c-4d3a-80d4-c51f55bc6bc6",
    github: "https://github.com/Pamela1600",
    linkedin: "https://www.linkedin.com/in/p%C3%A2-miguel-598a02217",
    curriculo: "https://docs.google.com/document/d/1Vooie2ikLta2W60v2gsMInmqOHg3om_7/edit?usp=sharing&ouid=111703281369057805072&rtpof=true&sd=true",
  },
  {
    name: "Ruan Pablo",
    area: "UX/UI Design",
    description: "<p>Sou o Ruan Pablo, tenho 18 anos. Moro em Paracatu-MG. Cursei Ensino de nível técnico em Eletrônica. Fascinado pela tecnologia e suas aplicações. Designer gráfico, aspirante a UI/UX Designer.</p>",
    image: "https://firebasestorage.googleapis.com/v0/b/techtuais-a0e95.appspot.com/o/RuanPablo.jpg?alt=media&token=8a441533-7662-48ac-948c-192fddc150b8",
    github: "https://github.com/Rpablo4",
    linkedin: "https://www.linkedin.com/in/ruan-pablo-38533520b/",
    curriculo: "https://drive.google.com/file/d/1-scc5ALln4NXtUTXJ_cmqfshrDiaIC30/view?usp=sharin",
  },
  {
    name: "Thaís Vitória",
    area: "Desenvolvedor Web",
    description: "<p>Me chamo Thais, tenho 17 anos. Faço serviços jurídico integrado ao ensino médio. Através da matemática, me interessei pela área de programação aos 10 anos e hoje dou continuidade.</p>",
    image: "https://firebasestorage.googleapis.com/v0/b/techtuais-a0e95.appspot.com/o/ThaisV2.png?alt=media&token=7cbc0eaa-bec0-4eac-897d-fc978e4eb217",
    github: "https://github.com/ThaisVitoriaFurquim",
    linkedin: "https://www.linkedin.com/in/tha%C3%ADsvit%C3%B3ria/",
    curriculo: "https://docs.google.com/document/d/e/2PACX-1vS8b8BCzr3zrGAiLzXjawb_j8t3GFHHrEzCXMmGqQsTImm5ouSc_GTABiyUNjQp6eWiX9yiaxdqpNHy/pub",
  }
]
